import argparse
import sys
import pickle

"""
Generates latex table using particular database, metric type (Recall, Precision or Reduction), r (records to test) value, given as arguments.
The script uses data generated by "run_tests_with_and_without_subgraphs.py" script, namely pickle file in a format:
    results/data/DATABASE-rRECORDS_TO_TEST-results.pkl

The resulting latex table is saved in a file "results/tables/DATABASE-rRESULTS_TO_TEST-METRIC-results.tex"
"""

MODELS = ["transe", "rotate", "complex", "distmult", "hole"]
SUBGRAPH_TYPES = ["star", "diamond"]
END_TYPES = ["H", "T"]
K_VALUES = ["10", "10%", "-1", "-2"]
SCORE_TYPES = ["avg", "kl", "nn"]
METRIC_TO_TYPE_STR_TRANSLATIONS = {"recall": "recall", "red": "red", "prec": "precision"}
HIGHLIGHT_LATEX_TEXT = {"prefix": "\\textbf{", "suffix": "}"}

DATA_DIR_PATH = "results/data/"
TABLE_DIR_PATH = "results/tables/"

def parse_args():
    parser = argparse.ArgumentParser(description = 'Construct latex tables from the experiment results')
    parser.add_argument('-db', dest = 'db', type = str, default = 'fb15k237')
    parser.add_argument('-r', dest = 'r', type = int, default = '-1', help = 'Number of records that were tested')
    parser.add_argument('--metric', dest = 'metric', type = str, default = 'recall', help = 'The metric of interest, either "Recall", "Precision" or "Reduction"')
    return parser.parse_args()

def compare_result_values(experiment_results, k, s, type_str):
    max_value = 0
    better_subgraph = "neither"
    for subgraph_type in SUBGRAPH_TYPES:
        result_value = float(experiment_results[subgraph_type][k][s][type_str])
        if result_value > max_value:
            max_value = result_value
            better_subgraph = subgraph_type
        elif result_value == max_value:
            better_subgraph = "neither"
    return better_subgraph

def generate_latex_line(model, r, metric):
    table_line_dict = dict()
    experiment_results = data[model]
    for subgraph_type in SUBGRAPH_TYPES:
        table_line_dict[subgraph_type] = dict()
        for end_type in END_TYPES:
            type_str = METRIC_TO_TYPE_STR_TRANSLATIONS[metric] + "_" + end_type
            table_line_dict[subgraph_type][end_type] = "& " + metric.capitalize() + "(" + end_type + ")" + f"$\\{subgraph_type}$ & "
            data_string = ""
            for k in K_VALUES:
                for s in SCORE_TYPES:
                    if compare_result_values(experiment_results, k, s, type_str) == subgraph_type:
                        data_string += HIGHLIGHT_LATEX_TEXT["prefix"] + str(experiment_results[subgraph_type][k][s][type_str]) + HIGHLIGHT_LATEX_TEXT["suffix"] + " &"
                    else:
                        data_string += str(experiment_results[subgraph_type][k][s][type_str]) + " &"
            table_line_dict[subgraph_type][end_type] += data_string[:-1] + "\\\\"

    return f"""\\multirow{{4}}{{*}}{{\\rotatebox{{90}}{{\\{model}}}}}
          {table_line_dict['star']['H']}
          {table_line_dict['star']['T']}
          {table_line_dict['diamond']['H']}
          {table_line_dict['diamond']['T']}
          """

def generate_latex_table(r, metric, fout):
    sys.stdout = fout
    print("\\begingroup")
    print("\\setlength{\\tabcolsep}{6pt} % Default value: 6pt")

    print("\\begin{tabular}{p{0.3em} p{4.5em} || ccc | ccc | ccc | ccc}")
    print("& \\multirow{2}{*}{\\em K} & \\multicolumn{3}{c}{10} & \\multicolumn{3}{c}{10\\%} & \\multicolumn{3}{c}{$Dyn$} & \\multicolumn{3}{c} {$Dyn^T$}\\\\")
    print("& & a & d & n & a & d & n & a & d & n & a & d & n \\\\")
    for model in MODELS:
        print("\\cline{2-14}")
        print(f"{generate_latex_line(model, r, metric)}")
    print("\\end{tabular}")
    print("\\endgroup")

args = parse_args()
args.metric = args.metric.lower()
if args.metric == "reduction":
    args.metric = "red"
if args.metric == "precision":
    args.metric = "prec"

with open(DATA_DIR_PATH + args.db + '-r' + str(args.r) + '-results.pkl', 'rb') as fin:
    data = pickle.load(fin)

with open(TABLE_DIR_PATH + args.db + '-r' + str(args.r) + '-' + args.metric + '-results.tex', 'w') as fout:
    generate_latex_table(args.r, args.metric, fout)