import argparse
import sys
import pickle

"""
Generates latex table using particular database, metric type (Recall, Precision or Reduction), r (records to test) value, given as arguments.
The script uses data generated by "run_tests_with_and_without_subgraphs.py" script, namely pickle file in a format:
    results/data/DATABASE-rRECORDS_TO_TEST-results.pkl

The resulting latex table is saved in a file "results/tables/DATABASE-rRESULTS_TO_TEST-METRIC-results.tex"
"""

DATA_DIR_PATH = "results/data/"
TABLE_DIR_PATH = "results/tables/"

def parse_args():
    parser = argparse.ArgumentParser(description = 'Construct latex tables from the experiment results')
    parser.add_argument('-db', dest = 'db', type = str, default = 'fb15k237')
    parser.add_argument('-r', dest = 'r', type = int, default = '-1', help = 'Number of records that were tested')
    parser.add_argument('--metric', dest = 'metric', type = str, default = 'recall', help = 'The metric of interest, either "Recall", "Precision" or "Reduction"')
    return parser.parse_args()

def generate_latex_line(model, r, metric):
    table_line_dict = dict()
    table_line_dict["star"] = dict()
    table_line_dict["diamond"] = dict()
    experiment_results = data[model]
    for subgraph_type in ["star", "diamond"]:
        for end_type in ["H", "T"]:
            type_str = metric + "_" + end_type
            table_line_dict[subgraph_type][end_type] = "& " + metric.capitalize() + "(" + end_type + ")" + f"$\\{subgraph_type}$ & "
            data_string = ""
            for k in ["10", "10%", "-1", "-2"]:
                for s in ["avg", "kl", "nn"]:
                    data_string += str(experiment_results[subgraph_type][k][s][type_str]) + " &"
            table_line_dict[subgraph_type][end_type] += data_string[:-1] + "\\\\"

    return f"""\\multirow{{4}}{{*}}{{\\rotatebox{{90}}{{\\{model}}}}}
          {table_line_dict['star']['H']}
          {table_line_dict['star']['T']}
          {table_line_dict['diamond']['H']}
          {table_line_dict['diamond']['T']}
          """

def generate_latex_table(r, metric, fout):
    sys.stdout = fout
    print("\\begingroup")
    print("\\setlength{\\tabcolsep}{6pt} % Default value: 6pt")

    print("\\begin{tabular}{p{0.3em} p{4.5em} || ccc | ccc | ccc | ccc}")
    print("& \\multirow{2}{*}{\\em K} & \\multicolumn{3}{c}{10} & \\multicolumn{3}{c}{10\\%} & \\multicolumn{3}{c}{$Dyn$} & \\multicolumn{3}{c} {$Dyn^T$}\\\\")
    print("& & a & d & n & a & d & n & a & d & n & a & d & n \\\\")
    print("\\cline{2-14}")
    print(f"{generate_latex_line('transe', r, metric)}")
    print("\\cline{2-14}")
    print(f"{generate_latex_line('hole', r, metric)}")
    print("\\cline{2-14}")
    print(f"{generate_latex_line('rotate', r, metric)}")
    print("\\cline{2-14}")
    print(f"{generate_latex_line('distmult', r, metric)}")
    print("\\cline{2-14}")
    print(f"{generate_latex_line('complex', r, metric)}")
    print("\\end{tabular}")
    print("\\endgroup")

args = parse_args()
args.metric = args.metric.lower()
if args.metric == "reduction":
    args.metric = "red"

with open(DATA_DIR_PATH + args.db + '-r' + str(args.r) + '-results.pkl', 'rb') as fin:
    data = pickle.load(fin)

with open(TABLE_DIR_PATH + args.db + '-r' + str(args.r) + '-' + args.metric + '-results.tex', 'w') as fout:
    generate_latex_table(args.r, args.metric, fout)